#!/usr/bin/env python3
"""Adds the cross-package `import`s the Milly-style split needs.

Builds a type -> package index from every package's Sources, then rewrites the
import block of each file (App, Packages, Tests) so it imports exactly the
packages whose public types it names. Idempotent.
"""
import os, re, sys, collections

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PKGS = os.path.join(ROOT, 'Packages')
APP = os.path.join(ROOT, 'App')
TESTS = os.path.join(ROOT, 'Tests')

MOD = r'(?:@\w+(?:\([^)]*\))?\s+|final\s+|indirect\s+)*'
TOP = re.compile(r'^' + MOD + r'public\s+' + MOD +
                 r'(?:struct|class|enum|actor|protocol|typealias|func|var|let)\s+(\w+)')

def walk(base):
    for dp, _, fns in os.walk(base):
        for fn in sorted(fns):
            # Package.swift is generated by scripts/gen-packages.py, not here
            if fn.endswith('.swift') and fn != 'Package.swift':
                yield os.path.join(dp, fn)

owner = {}
for p in walk(PKGS):
    rel = os.path.relpath(p, PKGS).split(os.sep)
    if 'Tests' in rel:
        continue
    module = rel[2] if len(rel) > 2 and rel[1] == 'Sources' else rel[0]
    for line in open(p):
        m = TOP.match(line)
        if m:
            owner[m.group(1)] = module

SWIFTUI_HINTS = (r'(^import SwiftUI$|: View\b|some View|\bColor\b|@State\b|@Binding\b|@Environment\b'
                 r'|\bViewBuilder\b|\bAnimation\b|\bCGFloat\b|\bFont\b|\bText\b|\bImage\b'
                 r'|\bShape\b|\bButtonStyle\b|\bGeometryEffect\b|\bUIColor\b|\bEdge\b)')

def needs_swiftui(src):
    return bool(re.search(SWIFTUI_HINTS, src, flags=re.M))

def imports_for(path, own_pkg):
    src = open(path).read()
    body = re.sub(r'^import .*$', '', src, flags=re.M)
    # comments are prose: a type named there is not a real reference
    body = re.sub(r'//.*$', '', body, flags=re.M)
    body = re.sub(r'/\*.*?\*/', '', body, flags=re.S)
    need = set()
    for name, pkg in owner.items():
        if pkg == own_pkg:
            continue
        if re.search(r'(?<![\w.])' + re.escape(name) + r'\b', body):
            need.add(pkg)
    # DesignSystem also vends View/Font/Color extensions (.gutter(), .page(),
    # .font(.title1)) that no type name reveals.
    # module-qualified references (`Money.Transaction`) name no bare type
    for module in set(owner.values()):
        if module != own_pkg and re.search(r'(?<![\w.])' + module + r'\.', body):
            need.add(module)
    if own_pkg != 'DesignSystem' and needs_swiftui(src):
        need.add('DesignSystem')
    return need

def rewrite(path, own_pkg, extra=()):
    src = open(path).read()
    lines = src.split('\n')
    keep = [l for l in lines if not re.match(r'^import \w+$', l)]
    while keep and not keep[0].strip():
        keep.pop(0)
    # imports that are not local packages (OSLog, Testing, UIKit...) are kept
    other = {m.group(1) for m in re.finditer(r'^import (\w+)$', src, flags=re.M)
             if m.group(1) not in owner.values() and m.group(1) != 'DesignSystem'}
    # Foundation types that no local module vends
    if re.search(r'\b(UUID|Date|Data|URL|Bundle|Locale|Calendar|NumberFormatter|DateFormatter'
                 r'|UserDefaults|NSLock|JSONEncoder|JSONDecoder|URLSession|URLRequest)\b', src):
        other.add('Foundation')
    other.discard('SwiftUI')
    if needs_swiftui(src):
        other.add('SwiftUI')
    mods = imports_for(path, own_pkg) | set(extra) | other
    # `@testable import X` already covers X; a plain `import X` is a duplicate
    mods -= {m.group(1) for m in re.finditer(r'^@testable import (\w+)$', src, flags=re.M)}
    mods = sorted(mods)
    open(path, 'w').write('\n'.join([f'import {m}' for m in mods] + [''] + keep))

if __name__ == '__main__':
    n = 0
    for p in walk(PKGS):
        rel = os.path.relpath(p, PKGS).split(os.sep)
        if rel[1] == 'Sources':
            own, extra = rel[2], []
        else:
            # Tests/<Module>Tests -> the module under test is imported explicitly
            own, extra = rel[2], [rel[2].removesuffix('Tests')]
        rewrite(p, own, extra)
        n += 1
    # App and Tests: imports come from the types actually named, not from a
    # fixed list, or the app target would end up importing PlatformTestSupport.
    for base in (APP, TESTS):
        if os.path.isdir(base):
            for p in walk(base):
                rewrite(p, '__app__')
                n += 1
    print(f'imports rewritten in {n} files')
    print('packages:', ' '.join(sorted(set(owner.values()))))
