// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoniPay.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MoniPay.Persistence.Migrations
{
    [DbContext(typeof(MoniPayDbContext))]
    [Migration("20260831094310_AddUsers")]
    partial class AddUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MoniPay.Users.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EmailCiphertext")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email_ciphertext");

                    b.Property<byte[]>("EmailLookupHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("email_lookup_hash");

                    b.Property<string>("FirstNameCiphertext")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name_ciphertext");

                    b.Property<string>("LastNameCiphertext")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name_ciphertext");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("locale");

                    b.Property<string>("PhoneCiphertext")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_ciphertext");

                    b.Property<byte[]>("PhoneLookupHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("phone_lookup_hash");

                    b.Property<Guid>("SignUpId")
                        .HasColumnType("uuid")
                        .HasColumnName("sign_up_id");

                    b.HasKey("Id");

                    b.HasIndex("EmailLookupHash")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email_lookup_hash");

                    b.HasIndex("PhoneLookupHash")
                        .IsUnique()
                        .HasDatabaseName("ix_users_phone_lookup_hash");

                    b.HasIndex("SignUpId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_sign_up_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("MoniPay.Users.Domain.UserConsent", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("DocumentKind")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("document_kind");

                    b.Property<DateTimeOffset>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<string>("DocumentVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("document_version");

                    b.HasKey("UserId", "DocumentKind");

                    b.ToTable("user_consents", (string)null);
                });

            modelBuilder.Entity("MoniPay.Users.Domain.UserConsent", b =>
                {
                    b.HasOne("MoniPay.Users.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_consents_users_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
