// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoniPay.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MoniPay.Persistence.Migrations
{
    [DbContext(typeof(MoniPayDbContext))]
    [Migration("20260906222702_AddSessions")]
    partial class AddSessions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MoniPay.Notifications.Domain.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("BodyCiphertext")
                        .HasColumnType("text")
                        .HasColumnName("body_ciphertext");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("channel");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("kind");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("last_error_code");

                    b.Property<DateTimeOffset?>("LeaseUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_until");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<string>("ProviderReference")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("provider_reference");

                    b.Property<string>("RecipientCiphertext")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recipient_ciphertext");

                    b.Property<string>("RecipientHint")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("recipient_hint");

                    b.Property<bool>("Required")
                        .HasColumnType("boolean")
                        .HasColumnName("required");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("SubjectCiphertext")
                        .HasColumnType("text")
                        .HasColumnName("subject_ciphertext");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_notifications_correlation_id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_notifications_idempotency_key");

                    b.HasIndex("Status", "NextAttemptAt")
                        .HasDatabaseName("ix_notifications_status_next_attempt_at");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("MoniPay.Sessions.Domain.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid?>("ReplacedById")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_id");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<byte[]>("TokenDigest")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("token_digest");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_refresh_tokens_expires_at");

                    b.HasIndex("SessionId")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_session_id_active")
                        .HasFilter("used_at IS NULL");

                    b.HasIndex("TokenDigest")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_digest");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("MoniPay.Sessions.Domain.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("RevokeReason")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("revoke_reason");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid>("TokenFamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("token_family_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_sessions");

                    b.HasIndex("TokenFamilyId", "DeviceId")
                        .IsUnique()
                        .HasDatabaseName("ix_sessions_token_family_id_device_id");

                    b.HasIndex("UserId", "RevokedAt")
                        .HasDatabaseName("ix_sessions_user_id_revoked_at");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("MoniPay.Sessions.Domain.SignUp", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BootstrapSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("bootstrap_session_id");

                    b.Property<DateTimeOffset>("CanResendAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("can_resend_at");

                    b.Property<byte[]>("CodeDigest")
                        .HasColumnType("bytea")
                        .HasColumnName("code_digest");

                    b.Property<DateTimeOffset?>("CodeExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("code_expires_at");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("failed_attempts");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("locale");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<string>("PhoneCiphertext")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_ciphertext");

                    b.Property<byte[]>("PhoneLookupHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("phone_lookup_hash");

                    b.Property<string>("PrivacyVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("privacy_version");

                    b.Property<Guid?>("ProvisionedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<byte[]>("RegistrationTokenDigest")
                        .HasColumnType("bytea")
                        .HasColumnName("registration_token_digest");

                    b.Property<int>("ResendCount")
                        .HasColumnType("integer")
                        .HasColumnName("resend_count");

                    b.Property<byte[]>("SignUpTokenDigest")
                        .HasColumnType("bytea")
                        .HasColumnName("signup_token_digest");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("status");

                    b.Property<string>("TermsVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("terms_version");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_sign_ups");

                    b.HasIndex("PhoneLookupHash")
                        .IsUnique()
                        .HasDatabaseName("ix_sign_ups_phone_lookup_hash")
                        .HasFilter("status IN ('CodePending', 'PhoneVerified', 'Locked')");

                    b.HasIndex("RegistrationTokenDigest")
                        .IsUnique()
                        .HasDatabaseName("ix_sign_ups_registration_token_digest")
                        .HasFilter("registration_token_digest IS NOT NULL");

                    b.HasIndex("SignUpTokenDigest")
                        .IsUnique()
                        .HasDatabaseName("ix_sign_ups_signup_token_digest")
                        .HasFilter("signup_token_digest IS NOT NULL");

                    b.HasIndex("Status", "ExpiresAt")
                        .HasDatabaseName("ix_sign_ups_status_expires_at");

                    b.ToTable("sign_ups", (string)null);
                });

            modelBuilder.Entity("MoniPay.Users.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name_ciphertext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name_ciphertext");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("locale");

                    b.Property<Guid>("SignUpId")
                        .HasColumnType("uuid")
                        .HasColumnName("sign_up_id");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("SignUpId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_sign_up_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("MoniPay.Users.Domain.UserConsent", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("DocumentKind")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("document_kind");

                    b.Property<DateTimeOffset>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<string>("DocumentVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("document_version");

                    b.HasKey("UserId", "DocumentKind")
                        .HasName("pk_user_consents");

                    b.ToTable("user_consents", (string)null);
                });

            modelBuilder.Entity("MoniPay.Users.Domain.User", b =>
                {
                    b.OwnsOne("MoniPay.Users.Domain.ProtectedContact", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Ciphertext")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("email_ciphertext");

                            b1.Property<byte[]>("Hash")
                                .IsRequired()
                                .HasColumnType("bytea")
                                .HasColumnName("email_lookup_hash");

                            b1.HasKey("UserId");

                            b1.HasIndex("Hash")
                                .IsUnique()
                                .HasDatabaseName("ix_users_email_lookup_hash");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("MoniPay.Users.Domain.ProtectedContact", "Phone", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Ciphertext")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("phone_ciphertext");

                            b1.Property<byte[]>("Hash")
                                .IsRequired()
                                .HasColumnType("bytea")
                                .HasColumnName("phone_lookup_hash");

                            b1.HasKey("UserId");

                            b1.HasIndex("Hash")
                                .IsUnique()
                                .HasDatabaseName("ix_users_phone_lookup_hash");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Phone")
                        .IsRequired();
                });

            modelBuilder.Entity("MoniPay.Users.Domain.UserConsent", b =>
                {
                    b.HasOne("MoniPay.Users.Domain.User", null)
                        .WithMany("Consents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_consents_users_user_id");
                });

            modelBuilder.Entity("MoniPay.Users.Domain.User", b =>
                {
                    b.Navigation("Consents");
                });
#pragma warning restore 612, 618
        }
    }
}
