// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoniPay.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MoniPay.Persistence.Migrations
{
    [DbContext(typeof(MoniPayDbContext))]
    partial class MoniPayDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MoniPay.Users.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name_ciphertext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name_ciphertext");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("locale");

                    b.Property<Guid>("SignUpId")
                        .HasColumnType("uuid")
                        .HasColumnName("sign_up_id");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("SignUpId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_sign_up_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("MoniPay.Users.Domain.UserConsent", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("DocumentKind")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("document_kind");

                    b.Property<DateTimeOffset>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<string>("DocumentVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("document_version");

                    b.HasKey("UserId", "DocumentKind")
                        .HasName("pk_user_consents");

                    b.ToTable("user_consents", (string)null);
                });

            modelBuilder.Entity("MoniPay.Users.Domain.User", b =>
                {
                    b.OwnsOne("MoniPay.Users.Domain.ProtectedContact", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Ciphertext")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("email_ciphertext");

                            b1.Property<byte[]>("Hash")
                                .IsRequired()
                                .HasColumnType("bytea")
                                .HasColumnName("email_lookup_hash");

                            b1.HasKey("UserId");

                            b1.HasIndex("Hash")
                                .IsUnique()
                                .HasDatabaseName("ix_users_email_lookup_hash");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("MoniPay.Users.Domain.ProtectedContact", "Phone", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Ciphertext")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("phone_ciphertext");

                            b1.Property<byte[]>("Hash")
                                .IsRequired()
                                .HasColumnType("bytea")
                                .HasColumnName("phone_lookup_hash");

                            b1.HasKey("UserId");

                            b1.HasIndex("Hash")
                                .IsUnique()
                                .HasDatabaseName("ix_users_phone_lookup_hash");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Phone")
                        .IsRequired();
                });

            modelBuilder.Entity("MoniPay.Users.Domain.UserConsent", b =>
                {
                    b.HasOne("MoniPay.Users.Domain.User", null)
                        .WithMany("Consents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_consents_users_user_id");
                });

            modelBuilder.Entity("MoniPay.Users.Domain.User", b =>
                {
                    b.Navigation("Consents");
                });
#pragma warning restore 612, 618
        }
    }
}
